"""First migration

Revision ID: 843781f2a07e
Revises: 
Create Date: 2025-02-11 14:46:35.917250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '843781f2a07e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_endpoint', sa.String(), nullable=False),
    sa.Column('pydantic_ai_wrapper', sa.String(), nullable=False),
    sa.Column('is_openai_compatible', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('user', 'system', name='typeenum'), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('lifetime_access', sa.Boolean(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_brief_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('author_instructions', sa.String(), nullable=False),
    sa.Column('writing_sample', sa.String(), nullable=False),
    sa.Column('negative_words', sa.String(length=200), nullable=True),
    sa.Column('product_info', sa.String(), nullable=True),
    sa.Column('call_to_action', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_brief_templates_user_id'), 'content_brief_templates', ['user_id'], unique=False)
    op.create_table('content_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('primary_keyword', sa.String(length=200), nullable=True),
    sa.Column('secondary_keywords', sa.String(), nullable=True),
    sa.Column('author_instructions', sa.String(), nullable=False),
    sa.Column('writing_sample', sa.String(), nullable=False),
    sa.Column('negative_words', sa.String(length=200), nullable=True),
    sa.Column('suggested_word_count', sa.Integer(), nullable=True),
    sa.Column('product_info', sa.String(), nullable=True),
    sa.Column('call_to_action', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_user_id'), 'content_briefs', ['user_id'], unique=False)
    op.create_table('content_outlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_brief_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_brief_id'], ['content_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_outlines_user_id'), 'content_outlines', ['user_id'], unique=False)
    op.create_table('content_outline_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_outline_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_outline_id'], ['content_outlines.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['content_outline_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('content_brief_id', sa.Integer(), nullable=False),
    sa.Column('content_outline_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_brief_id'], ['content_briefs.id'], ),
    sa.ForeignKeyConstraint(['content_outline_id'], ['content_outlines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_user_id'), 'contents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_user_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_table('content_outline_sections')
    op.drop_index(op.f('ix_content_outlines_user_id'), table_name='content_outlines')
    op.drop_table('content_outlines')
    op.drop_index(op.f('ix_content_briefs_user_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_content_brief_templates_user_id'), table_name='content_brief_templates')
    op.drop_table('content_brief_templates')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('prompts')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
